#!/bin/sh

cmd=$(tmux display -p '#{pane_current_command}')
cmd=$(basename "$cmd")
cmd=$(printf '%s' "$cmd" | tr '[:upper:]' '[:lower:]')

tmux resize-pane -Z
case "$cmd" in
  vi|vim|nvim|view|nview)
    sleep 0.05
    tmux send-keys C-w =
    ;;
esac
