#!/bin/sh

is_zoomed=$(tmux list-panes -F '#F' | grep -c Z || true)

case "${1:-}" in
  L) tmux select-pane -L ;;
  D) tmux select-pane -D ;;
  U) tmux select-pane -U ;;
  R) tmux select-pane -R ;;
esac

cmd=$(tmux display -p '#{pane_current_command}')
cmd=$(basename "$cmd")
cmd=$(printf '%s' "$cmd" | tr '[:upper:]' '[:lower:]')

if [ "${is_zoomed:-0}" -gt 0 ]; then
  tmux resize-pane -Z
  case "$cmd" in
    vi|vim|nvim|view|nview)
      sleep 0.05
      tmux send-keys C-w =
      ;;
  esac
fi
